### ISSUE TITLE
The exporter simply doesn't work

### ISSUE THREAD

**Issue by nimasarshar** [takahirox/glTF-Blender-IO-materials-variants#13]
Tried on 2.93.2 and 2.93.8 ...

**Comment by takahirox** [comment]
Thanks for the problem report. How it didn't work? Any error logs?

**Comment by nimasarshar** [comment]
No, but when I inspect it in the https://modelviewer.dev/editor/ there are no variants packed in the GLB. This one is meant to be a simple Cube with two textures: https://drive.google.com/file/d/1mWNRSkO-PBS-cHtqZ9Y8YgamF8QkanO-/view?usp=sharing
Thanks

**Comment by takahirox** [comment]
I speculate the root issue is same as #11.

Would you mind if trying potential solutions written in https://github.com/takahirox/glTF-Blender-IO-materials-variants/issues/11#issuecomment-972424441?

**Comment by LorenzWieseke** [comment]
Tried to use the add-on with gltf exporter 1.8.19 giving me:

gather_gltf_hook fails on <glTF-Blender-IO-materials-variants.glTF2ExportUserExtension object at 0x0000027E356D5BD0>
glTF2ExportUserExtension.gather_gltf_hook() takes 3 positional arguments but 5 were given

**Comment by takahirox** [comment]
We have released v0.0.3. Would you try it to check if the problem is still reproducible?

**Comment by takahirox** [comment]
Closing for now. Please reopen if the problem is still reproducible with the latest add-on.
