### ISSUE TITLE
Extention not in Root/Extentions

### ISSUE THREAD

**Issue by LorenzWieseke** [takahirox/glTF-Blender-IO-materials-variants#15]
Hi, 
first of all thanks for that add-on, it will allow our users to easily create different types of materials and later choose them in our online editor.

The first try was successful, simple cube and sphere:
![image](https://user-images.githubusercontent.com/29607121/157426402-0e2a7659-3958-4521-be45-f04864659a00.png)

But when I use a different model there is no "extensions" object on the root level, the meshes have it though:
![image](https://user-images.githubusercontent.com/29607121/157426780-319d0bbe-1e46-43b8-bc9e-2c8a74905700.png)
[Material_Variants.zip](https://github.com/takahirox/glTF-Blender-IO-materials-variants/files/8213956/Material_Variants.zip)

**Comment by LorenzWieseke** [comment]
As you can see, I also tried the newest gltf exporter but with no luck

**Comment by LorenzWieseke** [comment]
So I figured its working with the gltf exporter 1.7.33 (https://github.com/KhronosGroup/glTF-Blender-IO/tree/blender-v3.0-release) but not with older nor newer versions ;)

**Comment by GreyWorks** [comment]
A colleague and me tried to debug the problem.
The `gather_gltf_hook` was renamed to `gather_gltf_extensions_hook` in the exporter: https://github.com/KhronosGroup/glTF-Blender-IO/commit/28ac0983cf65144116817ff027e0a77a517e5e9a

Changing `gather_gltf_hook` to `gather_gltf_extensions_hook` in `__init__.py` makes the exporter functional again.
