### ISSUE TITLE
Not working with model-viewer

### ISSUE THREAD

**Issue by NikLever** [takahirox/glTF-Blender-IO-materials-variants#17]
I added 4 variants to the Blender default cube. When exporting a gltf there was no root level extensions block including the variant names. The extensions block at mesh level used names. I manually added the root level names block and change the mesh level extensions block to use indices not names and everything worked fine. In the end I switched to using the model-viewer editor to add variants. I reported this issue first on Twitter.

**Comment by takahirox** [comment]
From: https://twitter.com/NikLever/status/1516359516467646465

Thanks for the report and sorry for the slow response. Let me look into it hopefully soon.

**Comment by takahirox** [comment]
@NikLever Sounds like you use older add-on. Would you mind if checking that you use the latest add-on revision, 0.0.3? And if you use, would you please share how to reproduce with me in details?

I tried but exported correctly.

![image](https://user-images.githubusercontent.com/7637832/168502896-9871c634-3f00-4b0d-92e9-73456f9fd01e.png)

![image](https://user-images.githubusercontent.com/7637832/168502919-6d635a36-e5a7-41ba-ae2f-1fd6e772ab86.png)

**Comment by frankvoelker** [comment]
It is not working for me either.... I have a model, set material variants in Blender, exported as glb but in browser I get this:

![grafik](https://user-images.githubusercontent.com/70319084/169796005-622277f9-c24f-4636-97a4-afecad42c305.png)

I looked at the exported *.glb and see this

![grafik](https://user-images.githubusercontent.com/70319084/169796113-cd300878-0074-40b7-8cb6-54b8019bfa65.png)

**Comment by takahirox** [comment]
Thanks for the problem report. What Blender version and add-on version do you use?

**Comment by frankvoelker** [comment]
I was on 2.92 and now I upgraded to the latest version and now it works !

Maybe the readme should state to use latest Blender version :-)

**Comment by takahirox** [comment]
Thanks for checking.

Closing this issue. Please reopen if someone can still reproduce the problem.
